# Generated by Django 4.1.7 on 2023-03-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rolesssss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('Administrator', models.CharField(max_length=10)),
                ('Employee', models.CharField(max_length=10)),
                ('User', models.CharField(max_length=10)),
            ],
        ),
    ]
