# Generated by Django 4.1.7 on 2023-03-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rolesssss',
            new_name='Roles',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='Roles',
        ),
    ]
