# Generated by Django 4.1.7 on 2023-03-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_rename_rolesssss_roles_alter_roles_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
