# Generated by Django 4.1.7 on 2023-03-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drf', '0003_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('OS', models.CharField(max_length=25)),
                ('Push_token', models.DecimalField(decimal_places=100, max_digits=100)),
                ('Devices_ID', models.DecimalField(decimal_places=100, max_digits=100)),
            ],
            options={
                'db_table': 'Devices',
            },
        ),
    ]
