# Generated by Django 4.1.7 on 2023-03-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0007_device_device_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Device_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drf.device'),
        ),
    ]
