# Generated by Django 4.1.7 on 2023-03-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0008_alter_user_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Device_ID',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
