# Generated by Django 4.1.7 on 2023-03-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0009_remove_device_device_id_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='OS',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='Push_token',
        ),
        migrations.AlterModelTable(
            name='device',
            table='Test',
        ),
    ]
