# Generated by Django 4.1.7 on 2023-03-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0011_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterparty',
            options={},
        ),
    ]
